services:
  autocompose-gui:
    image: autocompose-gui:beta
    container_name: autocompose-gui
    restart: unless-stopped
    environment:
      - GITHUB_TOKEN=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
      - GITHUB_TARGET_REPO=roormonger/compose
      - GITHUB_UPLOAD_PATH=
      - GITHUB_UPLOAD_BRANCH=main
      - GITHUB_UPLOAD_COMMIT_MSG=
      - ENABLE_GITHUB_UPLOAD=true
      - FLASK_SECRET_KEY=lkanscvunwsoefnp343n
    labels:
      - AUTOCOMPOSE_EXCLUDE=GITHUB_TOKEN,FLASK_SECRET_KEY
    ports:
      - "8501:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - C:\auto:/generated_compose_files