services:
  autocompose-gui:
    image: roormonger/autocompose-gui:latest
    container_name: autocompose-gui
    restart: unless-stopped
    environment:
      - ENABLE_GITHUB_UPLOAD=false #Optional - Set to "true" to enable the "Upload to Github" button in the UI
      - GITHUB_TOKEN=YOUR_GITHUB_TOKEN #Optional - Your Github personal authorization token. Only needed for Github upload
      - GITHUB_TARGET_REPO=YOUR_GITHUB_REPO #Optional - The Github repo you want do dump your compose files into (NAME/REPO)
      - GITHUB_UPLOAD_PATH= #Optional - Path in the above repo. Leave blank for root
      - GITHUB_UPLOAD_BRANCH=BRANCH #Optional - Repo branch
      - GITHUB_UPLOAD_COMMIT_MSG= #Optional - The commit message. If blank default to "Autocompose-GUI_(TIMESTAMP)" 
      - FLASK_SECRET_KEY=YOUR_FLASK_KEY #Required - Make up whatever you want
    labels:
      - AUTOCOMPOSE_EXCLUDE=GITHUB_TOKEN,FLASK_SECRET_KEY #Optional - Add this to any container that has ENV variables you dont want in the output compose files. Just use a comma seperated list of ENV varibles to exclude
    ports:
      - "8501:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #Required
      - path/on/host:/generated_compose_files #Optional - You only need this if you plan on saving locally